package com.askcart.productservice.service;

import com.askcart.productservice.dto.ProductRequest;
import com.askcart.productservice.dto.ProductResponse;
import com.askcart.productservice.event.ProductCreatedEvent;
import com.askcart.productservice.mapper.ProductMapper;
import com.askcart.productservice.model.Product;
import com.askcart.productservice.repository.ProductRepository;
import org.springframework.kafka.core.KafkaTemplate;
import org.springframework.stereotype.Service;
import reactor.core.publisher.Mono;

import java.util.UUID;

@Service
public class ProductService {
    private final ProductRepository repository;
    private final KafkaTemplate<String, Object> kafkaTemplate;

    public ProductService(ProductRepository repository, KafkaTemplate<String, Object> kafkaTemplate) {
        this.repository = repository;
        this.kafkaTemplate = kafkaTemplate;
    }

    public Mono<ProductResponse> createProduct(ProductRequest request) {
        Product product = ProductMapper.toEntity(request);
        // ID is auto-generated by DB if null, or we can generate it here if R2DBC
        // requires it.
        // For Postgres UUID primary key with default gen_random_uuid(), we can leave it
        // null.
        return repository.save(product)
                .flatMap(savedProduct -> {
                    ProductCreatedEvent event = new ProductCreatedEvent(
                            savedProduct.getId(),
                            savedProduct.getName(),
                            savedProduct.getSku(),
                            savedProduct.getPrice(),
                            savedProduct.getCurrency(),
                            savedProduct.getCategoryId(),
                            savedProduct.getCreatedAt());
                    // Fire and forget style for now, or could link to reactive kafka
                    // Wrapping blocking Kafka send in Mono.fromRunnable or use
                    // ReactiveKafkaProducerTemplate if avail
                    // For now, simpler approach:
                    return Mono
                            .fromRunnable(
                                    () -> kafkaTemplate.send("product.events", savedProduct.getId().toString(), event))
                            .thenReturn(savedProduct);
                })
                .map(ProductMapper::toResponse);
    }

    public Mono<ProductResponse> getProduct(UUID id) {
        return repository.findById(id)
                .map(ProductMapper::toResponse);
    }
}
